properties([
        parameters(
                [
                        stringParam(
                                name: 'CHART_NAME',
                                defaultValue: 'admin-console'
                        ),
                        stringParam(
                                name: 'APP_VERSION',
                                defaultValue: '0.1'
                        ),
                        stringParam(
                                name: 'IMAGE_TAG',
                                defaultValue: ''
                        )
                ]
        )
])

pipeline {

    options {
            ansiColor('xterm')
            skipDefaultCheckout true
        }

    agent {
        kubernetes {
            yamlFile 'admin_console/deploy/builder.yaml'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                script {
                    if (IMAGE_TAG=="") {
                        error("Check entered parameters values: IMAGE_TAG or APP_VERSION. They must not be empty!")
                        currentBuild.result = 'ABORTED'
                    }
                    if (APP_VERSION=="") {
                        error("Check entered parameters values: IMAGE_TAG or APP_VERSION. They must not be empty!")
                        currentBuild.result = 'ABORTED'
                    }
                }
            }
        }



        stage('Clone git repo') {
            steps {
                container('git') {
                    script {
                        sh "git -C /kaniko/workspace/datagram_ci_cd stash"
                        sh "git -C /kaniko/workspace/datagram_ci_cd pull"
//                             sh "git clone https://github.com/zanzibeer/${params.CHART_NAME}_deploy.git"
                    }
                }
            }
        }
            
        stage('Deploy to env') {
            steps {
                container('helm-cli') {
                    script {
//                         sh "sleep 100"
                        sh "chmod +x /kaniko/workspace/datagram_ci_cd/admin_console/deploy/helm/setRevision.sh"
                        sh "chmod +x /kaniko/workspace/datagram_ci_cd/admin_console/deploy/helm/setImageTags.sh"
                        sh "/kaniko/workspace/datagram_ci_cd/admin_console/deploy/helm/setRevision.sh ${params.APP_VERSION}"
                        sh "/kaniko/workspace/datagram_ci_cd/admin_console/deploy/helm/setImageTags.sh ${params.IMAGE_TAG}"
                        sh "helm repo add bitnami https://charts.bitnami.com/bitnami"
                        sh "helm dependency build /kaniko/workspace/datagram_ci_cd/admin_console/deploy/helm"
                        sh "helm upgrade ${params.CHART_NAME} /kaniko/workspace/datagram_ci_cd/admin_console/deploy/helm --install --namespace ${params.CHART_NAME} --create-namespace \
                            --set postgresql.auth.password=\"postgres\" \
                            --set global.postgresql.auth.postgresPassword=\"postgres\""
//                         dir ("/kaniko/workspace/datagram_ci_cd") {
//                             sh "chmod +x ${params.CHART_NAME}/deploy/helm/setRevision.sh"
//                             sh "chmod +x ${params.CHART_NAME}/deploy/helm/setImageTags.sh"
//                             sh "${params.CHART_NAME}/deploy/helm/setRevision.sh ${params.APP_VERSION}"
//                             sh "${params.CHART_NAME}/deploy/helm/setImageTags.sh ${params.IMAGE_TAG}"
//                             sh "helm dependency build ${params.CHART_NAME}/deploy/helm"
//                             sh "helm upgrade ${params.CHART_NAME} ${params.CHART_NAME}/deploy/helm --install --namespace ${params.CHART_NAME} --create-namespace \
//                             --set postgresql.auth.password=\"chAngE_Me\""
//                         }
                    }
                }
            }
        }
    }
}
