properties([
        parameters(
                [
                        stringParam(
                                name: 'CHART_NAME',
                                defaultValue: 'datagram'
                        ),
                        stringParam(
                                name: 'APP_VERSION',
                                defaultValue: ''
                        ),
                        stringParam(
                                name: 'IMAGE_TAG',
                                defaultValue: ''
                        )
                ]
        )
])

pipeline {

    options {
        ansiColor('xterm')
        skipDefaultCheckout true
        disableConcurrentBuilds()
    }

    environment {
        WORKDIR = '/kaniko/workspace/datagram_ci_cd'
    }

    agent {
        kubernetes {
            yamlFile 'datagram/deploy/builder.yaml'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                script {
                    if (IMAGE_TAG=="") {
                        error("Check entered parameters values: IMAGE_TAG or APP_VERSION. They must not be empty!")
                        currentBuild.result = 'ABORTED'
                    }
                    if (APP_VERSION=="") {
                        error("Check entered parameters values: IMAGE_TAG or APP_VERSION. They must not be empty!")
                        currentBuild.result = 'ABORTED'
                    }
                }
            }
        }



        stage('Clone git repo') {
            steps {
                container('git') {
                    script {
                        sh "git -C ${WORKDIR} stash"
                        sh "git -C ${WORKDIR} pull"
                    }
                }
            }
        }
            
        stage('Deploy to env') {
            steps {
                container('helm-cli') {
                    script {
                        sh "chmod +x ${WORKDIR}/${params.CHART_NAME}/deploy/helm/setRevision.sh"
                        sh "chmod +x ${WORKDIR}/${params.CHART_NAME}/deploy/helm/setImageTags.sh"
                        sh "${WORKDIR}/${params.CHART_NAME}/deploy/helm/setRevision.sh ${params.APP_VERSION}"
                        sh "${WORKDIR}/${params.CHART_NAME}/deploy/helm/setImageTags.sh ${params.IMAGE_TAG}"
                        sh "helm dependency build ${WORKDIR}/${params.CHART_NAME}/deploy/helm/datagram"
                        sh "helm upgrade ${params.CHART_NAME} ${WORKDIR}/${params.CHART_NAME}/deploy/helm/datagram --install --namespace neoflex-${params.CHART_NAME} --create-namespace \
                        --set postgresql.auth.password=\"chAngE_Me\""
//                         dir ("${params.CHART_NAME}_deploy") {
//                             sh "chmod +x helm/setRevision.sh"
//                             sh "chmod +x helm/setImageTags.sh"
//                             sh "./helm/setRevision.sh ${params.APP_VERSION}"
//                             sh "./helm/setImageTags.sh ${params.IMAGE_TAG}"
//                             sh "helm dependency build helm/datagram"
//                             sh "helm upgrade ${params.CHART_NAME} helm/datagram --install --namespace neoflex-${params.CHART_NAME} --create-namespace \
//                             --set postgresql.auth.password=\"chAngE_Me\""
//                         }
                    }
                }
            }
        }
    }
}
